src/hdusd/engine/viewport_engine.py, src/hdusd/utils/__init__.py
Fixed possible issue with plugin activation. Issue #18.
Used bpy.utils.resource_path('LOCAL') instead of sys.executable (which could reference to blender.ex e or python.exe).
=> Fixed activation plugin for Blender 2.91+

src/hdusd/export/material.py, src/hdusd/export/mesh.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/mx_nodes/nodes/categories.py, src/hdusd/properties/__init__.py, src/hdusd/properties/material.py, src/hdusd/properties/object.py, src/hdusd/ui/__init__.py, src/hdusd/ui/material.py, src/hdusd/ui/mx_nodes.py
Assigning MaterialX (MX) node tree to object was working in developer mode, this process has to be made more user friendly.
1. Made MX node tree assign to blender material instead of object. Created panel for showing current Material with blender nodes or MX node tree. Added operator to select to use MX node tree or create new MX node tree.
2. Set Surfacematerial node as output node. Removed MX output node.
3. Implemented operator to create basic MX nodes in node tree.
4. During creating MX node tree in Material panel it also creates basic MX nodes and tries to open MX node tree window in blender UI.
5. Improved showing MX node sockets: output type, color. 
1. Moved link mx_node_tree from object properties to material properties.
2. Created MxNodeInputSocket and MxNodeOutputSocket. …
=> PRBLND-1612: Improve UI for assigning MaterialX to mesh

src/hdusd/bl_nodes/node_parser.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/ui/mx_nodes.py, src/hdusd/utils/__init__.py, src/hdusd/utils/mx.py
We are going to have possibility to import MaterialX (.mtlx) files into Blender MX node tree. Also this is needed for future MaterialX library.
1. Added possibility to import .mtlx files into Blender MX node tree.
2. Improved exporting MX nodes into .mtlx by not setting non-changed parameters and inputs.
1. Added utils/mx.py with useful functionality related to MX, moved some functions there.
2. Implemented MxNodeTree.import_() function which creates and places MX nodes in node tree from mx.Document.
3. Fixes/improvements:
- fixed double export of node by adding check if node was already exported;
- improved exporting of MX node by not setting non-changed parameters and inputs;
- improved showing some input sockets;
Currently it is available only to import .mtlx files when material is set …
=> RPRBLND-1663: Implement importing MaterialX files

src/hdusd/__init__.py, src/hdusd/bl_nodes/__init__.py, src/hdusd/properties/material.py
The existing Cycles/Eevee shader nodes menu doesn't works correctly with HdUSD plugin - it displays lots of nodes we aren't supporting while display no nodes in Shader category. The custom menu should be used instead.
Hide the Shader Editor nodes from menu that aren't supported by plugin. Display the supported nodes.
- limited Shade Editor shader nodes menu to nodes supported by plugin;
- fixed issue with rendering Blender material using the firstmost output node instead of active.
- added check for output shader node activity state;
- disable Cycles shader nodes menu categories;
- added custom menu with supported shader nodes.
=> [RPRBLND-1693] limit blender shader nodes menu to supported only

src/hdusd/engine/__init__.py, src/hdusd/utils/__init__.py, tools/generate_mx_classes.py
HDUSD_LIBS_DIR could be relative, this is used in CIS, therefore made appropriate changes.
Also there is a warning in log during loading hdRPR.
Fixed log warning in loading hdRPR.
Added absolute() to HDUSD_LIBS_DIR path.
Added HDUSD_LIBS_DIR/hdrpr/lib/python to system paths during loading plugin.
=> Fixed paths on CIS build and error with loading hdRPR

src/hdusd/bl_nodes/__init__.py, src/hdusd/bl_nodes/node_parser.py, src/hdusd/bl_nodes/nodes/__init__.py, src/hdusd/bl_nodes/nodes/color.py, src/hdusd/bl_nodes/nodes/converter.py, src/hdusd/bl_nodes/nodes/input.py, src/hdusd/bl_nodes/nodes/output.py, src/hdusd/bl_nodes/nodes/shader.py, src/hdusd/engine/engine.py, src/hdusd/engine/final_engine.py, src/hdusd/export/material.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/properties/material.py
Added export as MaterialX for Blender nodes Invert, MixRGB, Math, Glass BSDF, Value, RGB.
- added export as MaterialX for Blender nodes Invert, MixRGB, Math, Glass BSDF, Value, RGB.
- added more arithmetic helper operations using MaterialX;
- used arithmetic helper for MixRGB, Invert and Math nodes;
- added newly supported nodes to nodes menu;
- enabled check for node link validity to prevent loops parsing;
- added better errors logging for nodes parsing;
- fixed output socket parsing issue.
Textures requires additional work, will be added as a separate pull request
=> [RPRBLND-1677] Convert useful Blender nodes to materialX

src/hdusd/engine/engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/object.py, src/hdusd/export/world.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/usd_nodes/nodes/filter.py, src/hdusd/usd_nodes/nodes/merge.py, src/hdusd/usd_nodes/nodes/read_blend_data.py, src/hdusd/usd_nodes/nodes/usd_file.py
Some of USD nodes like Read Blender Data, Merge, Filter produce additional root prims which isn't useful and complicated. Much better would be to work with objects in the root of stage.
USD nodes Blender Data, Merge and Filter produce object prims in the root of stage.
1. Renamed classes ReadBlendDataNode -> BlenderDataNode, ReadUsdFileNode -> UsdFileNode as more related and simplified.
2. Adjusted Blender Data, Merge and Filter USD nodes to produce object prims in the root of stage.
3. Adjusted engines to produce object prims in the root of stage.
=> RPRBLND-1697: Use the "flattened" USD stage rather than one with merge nodes etc

src/hdusd/__init__.py
When standard surface MaterialX node is used HdRPR is very unstable and crashes randomly.
Fixed crashes when MaterialX standard surface node is used.
Updated min Blender version to 2.93 for this plugin.
Updated HdRPR submodule.
Set min Blender version 2.93.0 in bl_info
=> Updated HdRPR with standard surface crash fix.

src/hdusd/bl_nodes/node_parser.py, src/hdusd/bl_nodes/nodes/shader.py, src/hdusd/engine/preview_engine.py, src/hdusd/export/material.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/mx_nodes/nodes/categories.py, src/hdusd/properties/material.py, src/hdusd/properties/scene.py, src/hdusd/ui/material.py, src/hdusd/ui/mx_nodes.py, src/hdusd/ui/render.py, src/hdusd/utils/mx.py, tools/generate_mx_classes.py
Standard MaterialX nodes aren't good rendered by HdRPR. While RPR MaterialX nodes are fully supported. Therefore it'll be good to include them into plugin, and temporary set RPR Uber as default, until standard surface will be fully supported by HdRPR and HdStorm.
1. Added RPR MaterialX nodes
2. Added debug option "RPR MaterialX Nodes" into Debug panel.
3. Set RPR Uber as default MaterialX node if "RPR MaterialX Nodes" is enabled.
4. Made Principled node to convert into RPR Uber instead Standard surface if "RPR MaterialX Nodes" is enabled.
5. Fixed bug with finding camera in material preview.
1. Improved generate_mx_classes.py with better node categories and class names:
- Added RPR MaterialX nodes to generating MX classes process. 
- Added 'angle' type support.
-  Added _node_name to …
=> RPRBLND-1721: Support RPR MaterialX nodes

src/hdusd/engine/__init__.py, src/hdusd/engine/handlers.py, src/hdusd/properties/__init__.py, src/hdusd/properties/object.py, src/hdusd/properties/scene.py, src/hdusd/properties/usd_list.py, src/hdusd/ui/__init__.py, src/hdusd/ui/object.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/base_node.py, src/hdusd/usd_nodes/nodes/hydra_render.py, src/hdusd/utils/usd.py, src/hdusd/viewport/__init__.py, src/hdusd/viewport/usd_collection.py
We want export entire USD stage from selected USD node tree to be exported as empty objects into scene collection.
1. USD stage from selected viewport USD node tree is exported as empty objects into scene collection (called "USD NodeTree"). Created empty objects duplicate tree structure of USD stage. 
2. Added basic UI panel with USD object settings into Object tab.
3. Changes in USD node tree affect to USD NodeTree objects collection.
4. Made USD NodeTree objects collection to be not saved in .blend file.
1. Added vieport/usd_collection.py module, which works with USD NodeTree scene collection with empty objects: create, update, clear.
2. Added USDNode.node_computed() handler. Implemented HydraRenderNode.node_computed() to notify USD node tree output_node_computed() and update objects …
=> RPRBLND-1698: Add the entire USD stage, not just selected item to the USD collection as empty objects

src/hdusd/engine/engine.py, src/hdusd/engine/handlers.py, src/hdusd/export/object.py, src/hdusd/properties/object.py, src/hdusd/properties/usd_list.py, src/hdusd/ui/__init__.py, src/hdusd/ui/object.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/viewport/usd_collection.py
Export object properties of the USD empty objects that are edited in the blender scene
For example position, visibility, etc should be exported for each “empty object” in the USD collection as an edit layer on top of the USD node tree data.
USD empty objects now can change USD stage: like changing transform and showed more info about USD prim.
1. Adjusted ObjectProperties class to work with USD prim
2. Improved Object UI panel for showing USD Settings: name, path, change visibility. dded Show/Hide operator. Prepared to show more info.
3. Removed usage of UsdList item object as not needed.
4. Made some code improvements, renamings.
=> RPRBLND-1699: Export object properties of the USD empty objects that are edited in the blender scene

src/hdusd/engine/engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/viewport/usd_collection.py
When nodetree data source is selected for viewport, we want to see interactive updates of selected nodetree (node, scene changes) in viewport rendering.
Applied viewport render updates on USD node tree update, when nodetree data source is selected for viewport.
1. Made refactoring: splitted ViewportEngine to 2 classes ViewportEngine and ViewportEngineNodetree for easier maintanance.
2. Implemented notification system from USD nodetree output node stage changes to ViewportEngineNodetree:
- added set of references of ViewportEngineNodetree instances
- implemented ViewportEngineNodetree.nodetree_output_node_computed(), ViewportEngineNodetree.nodetree_stage_changed().
3. Improved algorithm of updating blender objects for USD tree in USD collection.
=> RPRBLND-1723: Call for scene update on USD nodegraph update

src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/ui/mx_nodes.py, src/hdusd/utils/mx.py
MaterialX <nodegraph> statement is not supported, therefore we cannot import mtlx files which have it and we cannot export MX node tree using this statement.
Implemented support of MaterialX <nodegraph> statement.
1. Adjusted MX import process to support <nodegraph>:
- adjusted MxNodeTree.import_() function
- added some functions to utils/mx.py
2. Adjusted MX export process to support <nodegraph>.
- adjusted MxNode.compute() function
- added/updated some functions in utils/mx.py
Currently MX <nodegraph> isn't implemented using blender node groups, because it is not available in MxNodeTree. I didn't find how to enable it, but spent significant time for this. Therefore import of nodes which are in nodegraph is placed inside MX node tree with name like: \<nodegraph name>/\<node name>.
=> RPRBLND-1756: Support MaterialX <nodegraph>

deps/UsdImagingLite/pxr/usdImaging/usdImagingLite/engine.cpp, deps/UsdImagingLite/pxr/usdImaging/usdImagingLite/engine.h, deps/UsdImagingLite/pxr/usdImaging/usdImagingLite/wrapEngine.cpp, src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/properties/__init__.py, src/hdusd/properties/hdrpr_render.py, src/hdusd/properties/scene.py, src/hdusd/ui/__init__.py, src/hdusd/ui/hdrpr_render.py, src/hdusd/ui/render.py
We need more render settings for final and viewport renderers. Also every renderer could have its own render settings.
Implemented render settings for HdRPR render delegate. Added devices, samples, quality, denosing UI panels for final and viewport renderers.
1. Added render settings property classes for HdRPR in properties/hdrpr_render.py
2. Added render setting UI panel classes for HdRPR in ui/hdrpr_render.py
3. Implemented _sync_render_settings() in FinalEngine and ViewportEngine. Adjusted code.
4. Implemented methods UsdImagingLiteEngine::SetRendererSetting() and additional GetRendererSetting(), GetRendererSettingsList().
5. Removed unused code usdImagingLite/engine.cpp: render(), render_old()
In this PR I decided not to do dynamically created render settings and UI panels from json …
=> RPRBLND-1367: USD render settings

src/hdusd/utils/mx.py
Relative path in MaterialX nodes is not supported,
Fixed relative path in MaterialX nodes,
Fixed by bpy.path.abspath
=> RPRBLND-1802: Add support for "//..\" texture file path naming.

src/hdusd/engine/engine.py, src/hdusd/ui/__init__.py, src/hdusd/ui/material.py
MaterialX node trees selection menu in Material panel shows all node trees including USD node trees and grouped node trees.
Fixed list of MaterialX node trees in selection menu in Material panel.
1. Created operators and menu: HDUSD_MATERIAL_OP_link_mx_node_tree, HDUSD_MATERIAL_OP_unlink_mx_node_tree, HDUSD_MATERIAL_MT_mx_node_tree.
2. Added menu and operators to HDUSD_MATERIAL_PT_material panle istead of template_ID.
=> RPRBLND-1798: Fix list of MaterialX node trees in Material 

src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/blender_data.py
Objects menu in Blender Data USD node shows all available objects including empty objects which were imported from from USD tree.
Collections menu in Blender Data USD node shows all available collections including USD Nodetree collection.
Fixed objects menu in Blender Data USD node.
Fixed collections menu in Blender Data USD node.
Created operators and menus for selecting object and collection. Adjusted BlenderData USD node to use our menus.
=> RPRBLND-1797: Fix list of objects in Blender Data USD node

src/hdusd/engine/handlers.py, src/hdusd/ui/material.py
Need to add support for workflow: select mesh -> material X editor switch to the material from this mesh
Implemented automatic switch to selected MaterialX node tree or Shader editor when selected object or material was changed.
Implemented ui.material.depsgraph_update() which tries to show correspondent MaterialX area with node tree or Shader area. Removed this code from HDUSD_MATERIAL_OP_new_mx_node_tree operator as not needed.
=> RPRBLND-1812: Automatic switch to selected mesh MaterialX if selected mesh

src/hdusd/properties/material.py
There was unhandled exceptions during node parsing.
Fixed unhandled exceptions if parser returns None.
Return None if node_parser.export() returns None
=> RPRBLND-1839: Blender crashes after switching material of object.

src/hdusd/export/light.py
Sun light is not supported now.
1. Added sun light support
2. Also added Spot light support
1. Fixed getting light transform in HdRPR https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/500
2. Implemented DistantLight for sun light.
3. Spotlight emulated via ShapingAPI.
Full quality doesn't support Spotlight fully (spot blend doesn't work).
=> RPRBLND-1804: add "Sun" (directional light) light source support for USD

tools/create_libs.py
There is an error in loading hdRpr.so in linux, it can't find some libs.
Fixed loading HdRpr on linux.
Applied rpath to some openexr libs
=> Fixed some linux libs

tools/create_libs.py
After https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/496 we have import bug:
```
Warning (secondary thread): in Tf_PyLoadScriptModule at line 122 of D:\amd-gpuopen\BlenderUSDHydraAddon\deps\USD\pxr\base\tf\pyUtils.cpp -- Import failed for module 'rpr.RprUsd'!
Traceback (most recent call last):
File "D:\amd-gpuopen\BlenderUSDHydraAddon\libs\hdrpr\lib\python\rpr\RprUsd\devicesConfiguration.py", line 17, in <module>
from hutil.Qt import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'hutil'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "D:\amd-gpuopen\BlenderUSDHydraAddon\libs\hdrpr\lib\python\rpr\RprUsd\__init__.py", line 13, in <module>
from . import devicesConfiguration
File …
```
=> Fixed PySide2 import bug during loading HdRPR

src/hdusd/engine/viewport_engine.py
Render region render not selected region
Rendered region matches selected render region.
- Changed render viewport borders.
=> RPRBLND-1810: render region option not working correct.

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/light.py, src/hdusd/ui/__init__.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/usd.py
Current light export implementation isn't good, because different we have to use different light intensity depending of render delegate. In viewport we have to resync lights when delegate is changed. Better solution is to use USD Variants where we can store delegate dependent values.
Improved light export implementation with using USD Variants.
Added "Print Root Layer To Console" operator to USD Nodes Tools panel.
1. Improved light export implementation with USD Variants. Improved light intensity calculations.
2. Added utils.usd.set_variant_delegate(), adjusted final and viewport engines to selecting USD variant depending of delegate.
3. Updated BlenderDataNode.depsgraph_update() with selecting default variant delegate.
4. For debug purposes, created operator …
=> RPRBLND-1851: Export objects with USD Variants depending of render delegate

src/hdusd/ui/hdrpr_render.py
AI Denoising for Final render activates in Viewport render menu, Expexted activate AI Denoiser in Final render settings.
Activate AI Denoiser in Final render settings
Fixed AI Denoiser activation at HDUSD_RENDER_PT_hdrpr_settings_denoise_final
=> RPRBLND-1827: AI Denoising not activating in Final render menu

src/hdusd/engine/engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/world/__init__.py, src/hdusd/export/world/node_parser.py, src/hdusd/export/world/nodes.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/image.py
World export implementation is outdated and was working in draft mode. We need more complex support of world nodes, make it work in USD nodes and in viewport.
Improved worlds export system with better world nodes support, make it work in USD nodes and available to change in viewport.
1. Created module export/world:
- added node_parser.py with NodeItem and NodeParser classes, which parses nodes in world node_tree
- reimplemented WorldData class, adjusted sync(), implemented sync_update() in export/world/\_\_init__.py
- implemented parsing of useful nodes used in world node_tree.
- removed export/world.py
2. Added world syncing to BlenderDataNode USD node, made code improvements.
3. Added world syncing to ViewportEngineScene, made code improvements
4. Added utils/image.py with …
=> RPRBLND-1813: World support

src/hdusd/engine/engine.py, src/hdusd/engine/final_engine.py, src/hdusd/utils/__init__.py
A stage is created from all the enabled collections, so in case if active camera isn’t there, it doesn’t include into the stage for final render.
Result: null camera is set as active render camera.
Active camera needs to be added to a stage separately.
Render collections with expected result and without errors
Added use_scene_cameras input for depsgraph_objects to be able exclude a camera for final render
Added sync camera object separately for final render
=> RPRBLND-1833: Collection render no working correct

src/hdusd/engine/viewport_engine.py
Viewport render doesn't work with GL delegate 
Viewport render with GL delegate works correctly
Obtaining statistic changed to "get" method with default value
=> Fix error in RPRBLND-1844

src/hdusd/engine/final_engine.py
get RuntimeError: Accessed schema on invalid prim after fix the collections render error. Found the error raises when a camera object and a camera data have different name.
Render as expected without an error.
Fixes when a camera object and a camera data names are different.
=> Fix error in RPRBLND-1833

src/hdusd/engine/engine.py, src/hdusd/engine/final_engine.py, src/hdusd/engine/preview_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/camera.py, src/hdusd/export/object.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/__init__.py
Object instances export isn't implemented yet. 
Implemented exporting of object instances for Final and Viewport renderes and for Blender Data USD Node.
Fixed setting correct resolution in camera export in some cases.
1. Created ObjectData dataclass in export/object.py. 
- Made it to work with scene object and scene instance.
- Moved depsgraph_objects() from utils/\_\_init__.py to ObjectData as more related
- adjusted object.sync(0 and object.sync_update() functions
2. Adjusted FinalEngine, ViewportEngine, BlendDataNode to work with ObjectData.
3. Fixed camera export by providing more correct scene resolution.
4. Refactoring, which will be helpful for future development:
- Splitted FinalEngine to FinalEngineScene and FinalEngineNodetree. .
- Reimplemented PreviewEngine, made it …
=> RPRBLND-1846: Scene Instances support

src/hdusd/export/mesh.py
Fix mesh sync, get expexted render result
Render as expected without an error
Added attribute data.uv_indices, set to None
In final render Camera object sync still goes after scene objects sync so in future maybe more camera errors but it will be easier to catch error of wrong object sync
=> RPRBLND-1881: 'MeshData' object has no attribute 'uv_indices'

src/hdusd/bl_nodes/node_parser.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py, tools/generate_mx_classes.py
Need to add support for material X channels animation, like in default blender materials and RPR plugin.
Our custom socket doesn't work with standard blender animation functionality.
Enable Keyframes support for nodes.
- Moved everything from MxNodeDef to MxNode
- Refactoring to work with MxNode instead of MxNodeDef
- Modified generator for mx classes
You need to regenerate mx-classes to get new MxNodes
Some nodes doesn't work (e.g separate) - the reason is more global.
=> RPRBLND-1820: add MaterialX channels animation support.

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/world/__init__.py, src/hdusd/usd_nodes/nodes/blender_data.py
GL delegate doesn't work properly with world light.
Viewport and Final render with GL delegate now uses world light.
- Added "transparency" parameter for WorldData class
- Added getting world light parameters for viewport and final renders
Didn't find transparency option for USD, so it doesn't work if source is USD file and transparency works only with GL delegate
=> RPRBLND-1870: GL delegate doesn't work properly with world light

src/hdusd/bl_nodes/node_parser.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/utils/mx.py, tools/generate_mx_classes.py
There are several issues related to MaterialX nodes: 
- bug in generate_mx_classes.py after #99 which produces `TypeError: 'float' object is not iterable`
- creating incorrect node during importing mtlx, especially noticeable with materials from matlib
- multioutput nodes aren't supported
Fixed bugs with creating incorrect node during import of mtlx, including materials from matlib.
Implemented support of multioutput nodes.
1. Fixes in generate_mx_classes.py:
- fixed bug which produces incorrect inputs types
- fixed nodedef_data_type(), now it returns correct nodedef data type
- made code improvements
2. Fixed `mx_nodes.nodes.get_mx_node_cls()`. Now returns correct MxNode class by comparing mx_node structure with nodedef structure.
3. Implemented support of multioutput node: 
- …
=> RPRBLND-1901: TypeError: 'float' object is not iterable

src/hdusd/utils/image.py
We need to change internal image Format, not just write extension to file.
Images saved now properly with correct extension and internal format.
- changed image.save_render() to image.save()
- added changing and reverting changes to image
To test if it works - this scene must be rendered: https://cloud.blender.org/p/gallery/5dd6d7044441651fa3decb56
=> RPRBLND-1927: Image caching doesn't take into account output properties.

src/hdusd/export/object.py
There are duplicates of existing objects if selected data source for viewport rendering is NodeTree
No more duplicates in outliner and USD 
Added check if object from depsgraph is from USD
=> RPRBLND-1931: Hierarchy of USD objects in outliner is not the same as in USD

src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/ui/__init__.py, src/hdusd/ui/material.py, src/hdusd/utils/mx.py
Add panel to UI with MaterialX settings to work with Node Tree similar to common Blender functionality
Now it is available to edit MaterialX node tree via UI in common Blender way.
- Added subpanel for surfaceshader
- Added subpanel for displacementshader
- Added possibility to add/remove/disconnect nodes to/from any available input in node tree and edit their values via UI.
- Added method draw_node_view of MxNode to draw node with links itself
- Added update of UI due to update of node tree
<br/>
- Added child panel surfaceshader for surfaceshader input of Surfacematerial node
- Added child panel displacementshader for displacementshader input of Surfacematerial node
<br/>
- Added separate operator to invoke popup window which contains list of available shader nodes to link to …
=> RPRBLND-1852: Add MaterialX settings to "Material Properties" UI.

src/hdusd/export/material.py
Material isn’t updated in viewport.
Material is updated in viewport.
Update references wirh new *.mtlx temp file.
Added ability to update 'material:binding' attribute  while switch to MaterialX or vice versa.
=> RPRBLND-1965: Material isn’t updated in viewport

src/hdusd/bl_nodes/nodes/texture.py, src/hdusd/export/world/__init__.py, src/hdusd/utils/image.py, src/hdusd/utils/mx.py
ERROR hdusd.engine: Error: Image 'roughness.png' does not have any image data.
No error if the image path is invalid or the image has no data.
Added check image.has_data in case "Can't load image".
Added log.warn for missing images.
=> RPRBLND-1969: ERROR hdusd.engine: Error: Image 'roughness.png' does not have any image data

src/hdusd/bl_nodes/nodes/shader.py
Fix not working Diffuse BSDF node
Enable support of Diffuse BSDF node.
- Changed created node from diffuse_brdf to standard_surface
- Adjusted inputs values
=> RPRBLND-1950: KeyError: 'BSDF' with USD_Hydra

src/hdusd/properties/material.py, src/hdusd/properties/matlib.py, src/hdusd/ui/__init__.py, src/hdusd/ui/matlib.py, src/hdusd/utils/matlib.py
Matlib implementation is initial and was made in one thread, therefore it is slow and freezes blender.
1. Improved speed of initial loading Material Libarary without freezing blender.
2. Improved UI for Material Libarary.
3. Implemented package downloading with downloading status and without freezing blender.
4. Made list of materials to be sorted by name and packages sorted by size.
1. Initial loading of materials is made in separate thread with ThreadPoolExecutor usage for parallel material info loading. 
2. Improved matlib cache structure. Made initial matlib loading firstly look into cache, secondly sync with server.
3. Improved matlib UI, made code improvements and optimizations.
4. Implemented package loading in separate thread with showing loading status in UI.
Some cases aren't …
=> RPRBLND-1934: Downloading matlib materials in separate threads

src/hdusd/utils/image.py
Investigated an issue with 'GENERATED' source images while caching. The image source is being changed from 'GENERATED' to 'FILE'.
Scene with 'GENERATED' source images renders as expected. 
Set back initial image.source after caching.
=> fix_RPRBLND-1969: Error: Image 'roughness.png' does not have any image data

src/hdusd/ui/__init__.py, src/hdusd/ui/material.py
Add convert button from blender shader to MatX nodes.
Add convert button at Material Property panel at MaterialX section. Transfers blender shader to MatX nodes.
Added new operator HDUSD_MATERIAL_OP_convert_mx_node_tree.
=> RPRBLND-1966: Add convert button from blender shader to MatX nodes

src/hdusd/properties/hdrpr_render.py
Only Northstar and HybridPro render qualities support MatX. Other can be excluded.
Excluded Legacy, High, Medium, Low render qualities from RPR render delegates, as they aren't support MaterialX.
Excluded mentioned items from render_quality.
=> RPRBLND-1994: Exclude MatX unsupported render qualities fro HdRPR.

src/hdusd/bl_nodes/__init__.py, src/hdusd/bl_nodes/node_parser.py, src/hdusd/export/world/node_parser.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/mx_nodes/nodes/categories.py, src/hdusd/ui/material.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/base_node.py, src/hdusd/utils/__init__.py
Add Reroute nodes to MaterialX, Shader/World Editor, USD Editor.
Optionally add Frame node.
Added Layout node category to MaterialX, Shader Editor, USD Editor.
Added Reroute and Frame nodes to MaterialX, Shader Editor, USD Editor.
Registered new category Layout in USD, MaterialX, Shader Editor.
Changed get_input_link method so it skips all NodeReroute objects. It's has done in MxNode, NodeParser, USDNode.
In HDUSD_MATERIAL_PT_material_settings_surface, HDUSD_MATERIAL_PT_material_settings_displacement, changed draw method so it skips all NodeReroute objects.
Changed _reset_next method so it skips all NodeReroute objects in USDNode.
=> RPRBLND-1370: Reroute nodes

src/hdusd/mx_nodes/nodes/base_node.py
Export error when MX node is connected to several inputs:
`LookupError: Child name is not unique`
Fixed export error with MaterialX node tree when MX node is connected to several inputs.
Fixed by creating property MxNode.mx_node_path with more correct node path calculation.
=> RPRBLND-1993: LookupError: Child name is not unique

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/light.py, src/hdusd/export/world/__init__.py, src/hdusd/properties/scene.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/usd.py, tools/build_usd.py
GL delegate doesn't work good when environment texture is set in Blender.
Fixed GL delegate rendering with environment texture: made workaround by disabling it for GL delegate.
1. Created add_delegate_variants() in utils/usd.py. Made some renamings and code improvements.
2. Set dome light texture via add_delegate_variants() with setting empty path for GL delegate. Adjusted othe code with add_delegate_variants().
3. Applied additional light in camera position in viewport for GL delegate and MATERIAL shading type.
4. Added additional buffer clearing in ViewportEngine.draw().
I didn't find the way how to fully fix that, therefore I made workaround by providing empty path to environment texture for GL delegate.
=> RPRBLND-1970: Bug with GL delegate in viewport with Enviroment texture

src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/ui/material.py
Error with an older scene that contains uber shader.
Works as expected for a scene with uber shader.
get a correct input index with output_node.inputs.find(self.bl_label).
made workaround to handle unsupported  nodes is_mx_node_valid.
=> fix_RPRBLND-1968: Improve MatX UI panel (should be more close to Blender Shading)

src/hdusd/properties/hdrpr_render.py
Rendering speed on some cards like Vega 56/64 is significant slower comparing to RX6800 and comparing to RPR plugin.
Increased overall HdRPR rendering speed by setting variance_threshold=0.05 by default.
Increased speed on some video cards like Vega 56/64.
Made forcing enabling of Lighting Compiler.
Set variance_threshold=0.05 by default.
=> Improving HdRPR render performance for some cards

src/hdusd/bl_nodes/__init__.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/categories.py, src/hdusd/ui/material.py, src/hdusd/usd_nodes/nodes/__init__.py
MX nodes aren't sorted comparing to blender's shader nodes.
Implemented sorting of MX nodes. Improved material UI panel with selecting MX node.
1. Added sorting of MX nodes by category and label.
2. Improved popup panel with selecting MX node in material panel + improved algorithm.
=> RPRBLND-2008: Add sorting to MX nodes in material UI and nodetree UI

src/hdusd/utils/image.py
Add support of ".dds" image format.
Added support of ".dds" image format.
Added constant READONLY_IMAGE_FORMATS and check for it for image formats, which blender can read, but can't write.
=> RPRBLND-2035: Fail rendering Bistro scene

requirements.txt, src/hdusd/config.py, src/hdusd/engine/engine.py, src/hdusd/engine/handlers.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/material.py, src/hdusd/properties/object.py, src/hdusd/properties/usd_list.py, src/hdusd/ui/__init__.py, src/hdusd/ui/object.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/stage_cache.py, src/hdusd/utils/usd.py, src/hdusd/viewport/usd_collection.py
Now in Blender user can not change any materials in imported USD files, need to add support assigning material for USD nodetree mesh prims.
Added possibility to assign material for selected USD NodeTree collection object. 
Added possibility to assign material for selected mesh prim in USD list in USD NodeTree.
Fixed some updating bugs with USD NodeTree collection objects.
1. Added material property to ObjectProperties and update_material() function to assign material.
2. Fixed updating bugs with USD NodeTree collections objects:
- added no_depsgraph_update_call() function into handlers which prevents for calling depsgraph_update for some calls.
- adjusted functions in viewport/usd_collection.py to use no_depsgraph_update_call()
3. Added traverse_stage in utils/usd.py for more flexible …
=> RPRBLND-1805: Add Materials settings for USD nodetree mesh prims

src/hdusd/properties/object.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/viewport/usd_collection.py
USD Transform, TransformByEmptyNode, InstancingNode nodes don't update empty objects in USD NodeTree outliner and viewport.
Now empty updates immediately.
Added method sync_transform_from_prim to ObjectProperties.
Excluded empty object from depsgraph_update method for BlenderDataNode.
Recursion issues found while handing the task were fixed. It's good to test various nodetree cases.
=> RPRBLND-1949: USD Transform node doesn't update empty objects in USD NodeTree outliner

src/hdusd/usd_nodes/node_tree.py
Frame node causes an error in USD nodetree.
Frame node works as expected in USD nodetree.
In USDTree fixed condition in methods: _reset_nodes, depsgraph_update, frame_change, material_update
=> RPRBLND-2048: Frame node causes an error in USD nodetree

src/hdusd/config.py
Online matlib is ready to be open for users.
Enabling Matlib panel in Materials tab.
Set config.matlib_enabled = True
=> Enabling matlib by default in config.py

src/hdusd/properties/hdrpr_render.py, tools/create_libs.py
CIS:REBUILD_DEPS
RPR Core to 2.2.10 is available.
Updated RPR Core to 2.2.10.
Set deps\HdRPR submodule to origin:core-2.2.10_no-usd-schema
Improved build script.
We can't use latest HdRPR currently because of https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/508. 
To use USD schema for HdRPR will be done in separate task.
=> RPRBLND-2042: Update HdRPR with Core 2.2.10.

tools/build_usd.py
CIS:REBUILD_DEPS
There was an error in providing arguments to MaterialX build.
Fixed error during building of MaterialX.
Fixed arguments provided to materialx build: added python executable, added --verbose.
=> Fixed arguments provided to materialx build + Linux build fix

src/hdusd/engine/final_engine.py, src/hdusd/properties/hdrpr_render.py, src/hdusd/ui/__init__.py, src/hdusd/ui/hdrpr_render.py
Add "Film Transparent Background" option for HDRPR final render.
Added Film subpanel with Transparent Background option for HDRPR final render.
Added class HDUSD_RENDER_PT_hdrpr_settings_film_final.
Added description to property enable_alpha, set the default to False as in blender.
Connected render settings with enable_alpha property.
=> RPRBLND-2045: add "Film Transparent Background" option

src/hdusd/engine/viewport_engine.py
Fix updating materials in viewport after HdRPR update
Fixed updating materials during active viewport render.
Actualized name of render setting for identifying do we need to restart renderer.
=> RPRBLND-2060: Fix updating materials in viewport after HdRPR update

src/hdusd/engine/viewport_engine.py
Materials become orange if user clicks on scene in viewport render using GL delegate
Fixed issue with GL delegate in viewport render when materials become orange if user clicks in scene
added parameter `l.isDomeLight = True` for SimpleLight. Now it's created every time for GL delegate
There is the same issue with material preview, which can't be fixed right now.
Warnings in console:
- `Dome light has no texture asset path.` 
- `Invalid texture for dome light environment map`
- `Could not open dome light texture file`
also known and can't be fixed right now
=> RPRBLND-2030: Selected light source showed orange with GL Delegate

src/hdusd/mx_nodes/nodes/base_node.py
Replace UI_EMBOSS_NONE_OR_STATUS with NONE_OR_STATUS in UILayout.emboss for Blender3.0.
Fixed issue when linking two nodes in MaterialX editor in Blender 3.0.
Added condition for blender 3.0 and higher versions.
=> RPRBLND-2069: Blender 3.0 MaterialX editor error while link nodes and open Material Properies

src/hdusd/bl_nodes/node_parser.py, src/hdusd/export/world/node_parser.py, src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/ui/material.py
Fix an error with parsing MaterialX when input and output types of connected node's sockets.
Node's link in MaterialX nodetree editor now becomes invalid when types of output and input node's sockets are different.
Fixed switch to MaterialX nodetree editor if secondary window of blender are opened.
Added update_links() method to MxNodeTree.
It is used when Blender calls update() of MxNodeTree and depsgraph_update of ui/material.py.
In depsgraph_update now iterates throught all context.window_manager.windows.
In MaterialX node editor now links become red/invalid and nodes aren't calculated. To have the correct render result, the user needs to define all socket types properly before rendering.
=> RPRBLND-1990: path_tracer_shade.h:41: '' : syntax error, unexpected IDENTIFIER

src/hdusd/ui/material.py, src/hdusd/ui/panels.py, src/hdusd/utils/mx.py
Need to fix material X Editor workflow, because now MaterialX selection doesn't work as expected.
Improved MaterialX nodetree editor behavior when selecting MaterialX through Material Properties.
Added update_material_iu function.
Added turn on/off for bpy.types.NODE_HT_header updates.
Added condition for nodetree pin option.
There's a workaround for Blender 3.0 because of changing logic. For Blender 3.0 implemented only the pin option.
=> RPRBLND-2016: Improve Material X editor workflow

src/hdusd/utils/matlib.py
Download materials to Material Library via blender console.
Download materials to Material Library via blender console using bpy.ops.hdusd.matlib_load().
Added condition to check self.pcolls existance.
=> RPRBLND-2081: Download materials to Material Library via blender console

src/hdusd/utils/image.py
Fix image caching behavior
Fixed Preview Material infinite render loop with black result. 
Fixed caching image with relative path regardless of image format.
Fixed infinite loop of Preview Material render if Generated texture presents in nodetree.
Edited/unsaved images now caches regardless of image format, render result is similar to Cycles.
=> RPRBLND-2091: Fix image caching behavior

src/hdusd/usd_nodes/nodes/blender_data.py
Fix issue with not rendered objects if Data Source is NodeTree and parent of object is Empty object.
Fixed issue with not rendered objects if Data Source is NodeTree and parent of object is Empty object.
Fix wrong getting add/remove keys in blender_data node
=> RPRBLND-2071: Blender Data USD nodes issue.

src/hdusd/ui/usd_list.py
Fix export usd to file with unchecked checkbox "Pack into one file".
Fixed export error with unchecked checkbox "Pack into one file".
Small code improvements.
=> BLEN-49: Fix export usd to file with unchecked checkbox "Pack into one file"

src/hdusd/bl_nodes/nodes/shader.py
Improve Principled BSDF results.
Fixed while converting PrincipledBSDF to Standart Surface, all some color sockets were inherited from Base Color, now they use RGB (1.0, 1.0 1.0).
Added const DEFAULT_WHITE_COLOR.
Replaced base_color with DEFAULT_WHITE_COLOR.
Commented temporary useless code.
=> BLEN-14: improve Principled BSDF results

src/hdusd/properties/material.py
Fix exception if nodetree isn't exist for material.
Render and material UI panel works fine if nodetree isn't exist for material.
Added check for nodetree existence.
=> BLEN-58: Error with Country-Kitchen Cycles scene

src/hdusd/ui/material.py
Error if ShaderNode editor is open and no object in scene.
Incorrect behavior if shader_type is 'WORLD'.
Fixed incorrect behavior of ShaderNode editor in World mode.
Fixed error if ShaderNode editor is open and no object in the scene.
Fixed behavior if shader_type is 'WORLD'.
=> fix_RPRBLND-2016: Improve Material X editor workflow

tools/build.py, tools/build_usd.py, tools/create_libs.py
For debugging purposes in USD, UsdImagingLite, HdRPR projects we need ability to compile in Debug or RelWithDebInfo build variant.
Added 'release' (default) and 'relwithdebuginfo' build variants to the plugin build process.
Added 'release' and 'relwithdebuginfo' build variants to build.py script. With 'relwithdebuginfo' varint it also copies *.pdb files to the libs folder.
Added only 'release' and 'relwithdebuginfo' variants, 'debug' variant doesn't work properly.
CIS:REBUID_DEPS
=> Improvements in build process: added build variant option.

src/hdusd/engine/viewport_engine.py
Fix #200 
Viewport is correctly updated after changing render mode
Added condition to check if we need to re-create renderer
=> BLEN-55: [Community] Changing render mode sometimes doesn't update enabled viewport render

src/hdusd/export/light.py
Fix Direction light discrepancy for GL delegate
Direction light for GL delegate looks more similar to RPR delegate
Added coefficient for Intensity approximated to follow RPR results
=> BLEN-16: add Direction light support for GL delegate

src/hdusd/viewport/usd_collection.py
Fix crash with Undo operation if data source is NodeTree
Blender doesn't crash after Undo operation if data source is NodeTree
Added check for Undo operation.
=> Fix crash with Undo operation if data source is NodeTree

src/hdusd/engine/viewport_engine.py
Fix instances transform is not updated with active viewport render
Fixed instances transform is not updated with active viewport render
Added check for parent object name
=> BLEN-65: Scene Instances transform not update with active viewport render

src/hdusd/engine/final_engine.py
Add USD animation support for Final render.
Added support of animation for final render and USD node tree.
Passed current frame to 'frame' parameter for final render RPR and GL delegates.
=> BLEN-13: add USD animation support for Final render

README.md, deps/UsdImagingLite/pxr/usdImaging/usdImagingLite/engine.cpp, deps/UsdImagingLite/pxr/usdImaging/usdImagingLite/engine.h, src/hdusd/engine/final_engine.py, src/hdusd/engine/preview_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/properties/scene.py, tools/build.py
Add support for RenderMan render delegate
Added RenderMan render delegate
- Added flags for build script
- UsdImagingLite fixed for correctly setting clearColor
- Added try ... except for Render method due to known RenderMan issue
- Render method in preview and final renders moved under while(true) loop
- _sync_render_settings now returns bool to indicate if it finished ok
Known issue: https://github.com/PixarAnimationStudios/USD/issues/1415
USD doesn't have implementation for RenderMan rendering progress (renderer.GetRenderStats() doesn't have 'percentDone')
Material with image as texture doesn't work (likely because RenderMan has its own nodes for this)
To make RenderMan works you need to set environment variables https://graphics.pixar.com/usd/release/plugins_renderman.html#running-hdpr …
=> BLEN-44: PRman render delegate support

.gitignore, src/hdusd/mx_nodes/node_tree.py, src/hdusd/ui/matlib.py
Some of mtlx from matlib imported with errors, because some nodes are not supported.
Fixed importing of some mtlx files from matlib.
1. Added log error if required node isn't found in mtlx instead raise exception.
2. Fixed issue with arranging and placing of imported nodes, improved and simplified algorithm.
=> BLEN-67: MaterialX import error

src/hdusd/bl_nodes/node_parser.py, src/hdusd/bl_nodes/nodes/output.py, src/hdusd/bl_nodes/nodes/texture.py
Update Material X converter.
Improved Material X converter.
Added OUTPUT_TYPE constant that maps blender and materialx output types.
Added get_output_type() method to get dynamically output type of node according to linked socket.
Improved cached_nodes keys with output_type. A unique cache key allows the creation of a specific node for every output type.
=> BLEN-69: Update Material X converter

src/hdusd/export/camera.py, src/hdusd/export/object.py, src/hdusd/properties/scene.py, src/hdusd/ui/__init__.py, src/hdusd/ui/render.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/viewport/usd_collection.py
Add camera selection for viewport render settings.
Added ability to choose viewport camera from USD node tree.
Added constant name for viewport camera 'USD Camera'.
BLEND-66: add camera selection for viewport render settings.
Excluded 'USD Camera' from export to usd collection blender_data node in usd nodetree.
Improved CameraData adding init_from_usd_camera and export_to_camera.
Added new menu class HDUSD_MT_nodetree_camera_viewport.
Improved UI in render.py adding HDUSD_MT_nodetree_camera_viewport dropdown list.
Improved camera switch update with context.scene.hdusd.viewport.nodetree_update
Moved method nodetree_update to RenderSettings as now it's used by FinalRenderSettings, ViewportRenderSettings.
Added camera icon to the dropdown menu.
Some USD camera attributes might transfer …
=> BLEN-66: add camera selection for viewport render settings

src/hdusd/engine/final_engine.py, src/hdusd/export/object.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/usd_nodes/nodes/usd_file.py, src/hdusd/usd_nodes/nodes/write_file.py, src/hdusd/utils/usd.py
Add animation Import-Export support.
Added animation support for nodes (Blender Data, USD file, Write USD file) and exporting USD to file.
- Corresponded UI changes for Blender Data, USD file, Write USD file nodes and exporting USD to file;
- added reading and setting endTimeCode and startTimeCode to USD;
- added setting timeSamples to object transform;
- added auxiliary methods for setting USD timecodes to utils/usd.py;
=> BLEN-70: add animation Import-Export option for USD nodes

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/properties/__init__.py, src/hdusd/properties/hdprman_render.py, src/hdusd/properties/scene.py, src/hdusd/ui/__init__.py, src/hdusd/ui/hdprman_render.py
Add RenderMan delegate samples option.
Add RenderMan delegate Samples, Pixel Variance, and Timeout parameters.
Improved _sync_render_settings for final and viewport render as well.
Added Prman properties hdprman_render.py.
- RenderSettings
- samples
- variance_threshold
- timeout
Added Prman UI hdprman_render.py.
- HDUSD_RENDER_PT_hdprman_settings_final
- HDUSD_RENDER_PT_hdprman_settings_samples_final
- HDUSD_RENDER_PT_hdprman_settings_viewport
- HDUSD_RENDER_PT_hdprman_settings_samples_viewport
Added all parameters that are currently supported by USD.
=> BLEN-105: Add RenderMan delegate samples option

src/hdusd/engine/handlers.py, src/hdusd/properties/scene.py
Fix issue when scene was saved with render delegate which doesn't exist on current Blender.
Fixed issue when scene was saved with render delegate which doesn't exist on current Blender.
Added check in handler for chosen render delegate.
=> BLEN-173: Empty Render Delegate on systems without Render man delegate

src/hdusd/export/world/__init__.py
Possible issue during importing usd file in USD nodetree
```
File "D:\amd-gpuopen\BlenderUSDHydraAddon\src\hdusd\engine\viewport_engine.py", line 521, in _sync
self.render_params.clearColor = world_data.clear_color
Boost.Python.ArgumentError: Python argument types in
None.None(RenderParams, tuple)
```
Fixed possible issue during importing usd file in USD nodetree.
Added check `is not None` in WorldData.init_from_stage()
=> Fixed possible issue during importing usd file in USD nodetree.

src/hydrarpr/engine.py
Enable MaterialX usage for RPRHydraRenderEngine
set `bl_use_materialx = True`
=> Enable MaterialX

.gitignore, .gitmodules, build.py, src/resolver/__init__.py, src/resolver/config.py, src/resolver/logging.py, src/resolver/operators.py, src/resolver/properties.py, src/resolver/resolver.py, src/resolver/ui.py
Initial implementation
Move code from ResolverBlenderAddon to BlenderUSDHydraAddon
Only `Windows` support at this point.
* Added submodules `deps/Boost`, `deps/RenderStudioKit`.
* Added ResolverBlenderAddon source code to `src/resolver'.
* Updated build script with methods `resolver`, `zip_rs_addon`, `boost` and flags `-rs`, `-rs-addon`, `-boost` respectively:
* `-rs` - building RenderStudioKit libs,
* `-rs_addon` - Creating zip addon,
* `-boost` - building Boost 1.80.0 libs, it's required only `boost::python` and  `boost::log`, we build our own `boost` as far as    `boost::log` (mandatory for RenderStudioKit ) is not provided within Blender libs.
We can build RenderStudioResolver addon using flags:
`-all` or `-materialx -usd -boost -rs -rs-addon`
RenderStudioKit also requires dependency …
=> BLEN-577: Move code from ResolverBlenderAddon to BlenderUSDHydraAddon

src/resolver/__init__.py, src/resolver/config.py, src/resolver/operators.py, src/resolver/properties.py, src/resolver/resolver.py, src/resolver/ui.py
Use USD stage exported from Blender.
Added Connect/Disconnect button to UI.
Removed User ID from UI.
Usd filename is generated using `used_id` and blender filepath and is saved at `render_studio_dir` (~/Documents/AMD RenderStudion Nome)
* Removed `RESOLVER_object_properties`. And made code adjustments.
* Removed `user_id` from UI and its property as well.
* Removed operators: `RESOLVER_OP_process_live_update`, `RESOLVER_OP_open_stage_uri`, `RESOLVER_OP_import_stage` and adjusted ui.
* Removed redundant function `get_transform_local`.
* Added `render_studio_dir` and `user_id` to config.
* Added operators: `RESOLVER_OP_connect`, `RESOLVER_OP_disconnect`.
* Added methods `connect`, `disconnect`, `connect_server`, `export_scene`, `open_usd`, property `is_connected`.
* Removed redundant code.
=> BLEN-579: Use USD stage exported from Blender

src/hydrarpr/render_studio/properties.py, src/hydrarpr/render_studio/resolver.py
Update RenderStudiKit submodule to enable file synchronization
* Update RenderStudioKit submodule.
* Adjusted code according to the RenderStudioKit API
* Removed redundant sync method.
RenderStudioKit issue
error | Asset resolver does nothing in Resolve() (pxrInternal_v0_23__pxrReserved__::RenderStudioResolver::_Resolve:218)
warn  | Can't find layer with id: studio:/BlenderUser_10bfa785-e4fb-4d31-a596-bef0cc332608_.usda (pxrInternal_v0_23__pxrReserved__::RenderStudioLayerRegistry::GetByIdentifier:69)
=> BLEN-585: Update RenderStudiKit submodule to enable file synchronization

.gitignore, src/hydrarpr/__init__.py, src/hydrarpr/preferences.py, src/hydrarpr/render_studio/resolver.py
Move addon settings to preferences.
Added Preferences panel with fields:
* Storage Dir - Set directory which would be synchronized for all connected users.
* Server Address - Set address of remote live server.
* Storage Address - Set address of remote assets storage.
* User ID - Set unique user identifier.
* Channel ID - Set channel identifier.
Implemented class `RPR_HYDRA_ADDON_PT_preferences`.
Added properties `rs_storage_dir`, `rs_server_url`, `rs_storage_url`, `rs_user_id`, `rs_channel_id`.
Added support of `configdev.py`.
Added `configdev`.py to `.gitignore`.
Code adjustments.
=> BLEN-586: Move addon settings to preferences

src/hydrarpr/preferences.py, src/hydrarpr/properties.py, src/hydrarpr/render_studio/operators.py, src/hydrarpr/render_studio/resolver.py, src/hydrarpr/render_studio/ui.py
Update RenderStudio panel design to fit file synchronization needs.
Renamed titles of preferences and panel to AMD RenderStudio.
Added checkbox Live Sync to toggle between manual and automatic Usd export.
Added button Sync Scene, Start Live Sync, Stop Live Sync.
Removed button `Export Stage to Console`
Removed Connect/Disconnect button from Outliner header.
Renamed operator's `bl_idname` "rs_resolver." -> "render_studio."
Added operator `RESOLVER_OP_sync_scene`.
Added operator `RESOLVER_OP_start_live_sync`.
Added operator `RESOLVER_OP_stop_live_sync`.
Resolver class added properties `self.status`, `self.is_syncing`.
Added RenderStudio properties class `RenderStudioSettings`, `live_sync` in particular.
Moved rename ui name of `RS_RESOLVER_PT_resolver` panel to `AMD RenderStudio`.
Renamed …
=> BLEN-588: Update RenderStudio panel design

src/hydrarpr/properties.py, src/hydrarpr/render_studio/__init__.py, src/hydrarpr/render_studio/resolver.py
* Moved handlers to `start_live_mode` and `stop_live_mode` methods respectively.
* Removed `register` method and improved `unregister`.
* Fixed: if disable `Live Sync` it still performs sync, now it stops live sync.
=> BLEN-582: Add scene update handlers: Live sync mode

src/hydrarpr/__init__.py, src/hydrarpr/preferences.py, src/hydrarpr/properties.py, src/hydrarpr/render_studio/resolver.py, src/hydrarpr/render_studio/ui.py
* Added property `rs_enable` to register/unregister `render_studio`.
* Added property `rs_file_format` to set extension for sync file.
* Added `Sync Settings` panel to be able to set up sync directory and sync file name.
* Added `Usd Settings` panel to expose usd export settings.
* Set the default `Storage Dir` to `../AppData/Roaming/AMD RenderStudio Home`.
* Removed Status.
=> BLEN-602: Make file sync path more human readable. Add more sync settings

src/hydrarpr/preferences.py, src/hydrarpr/properties.py, src/hydrarpr/render_studio/operators.py, src/hydrarpr/render_studio/resolver.py, src/hydrarpr/render_studio/ui.py
* Added ability to set up Workspace URL (remote server address)
* Update `RenderStudioKit` submodule with https://github.com/Radeon-Pro/RenderStudioKit/pull/19.
* UI alignment improvements.
* Removed `Relative Paths`, it is `True` by default.
=> BLEN-606: Add support for workspace URL

build.py, src/hydrarpr/preferences.py
* Hide RenderStudio preferences for Linux and MacOS.
* Disabled RenderStudioKit and Boost build for Linux And MacOS.
* Fixed Python dependency.
=> Fix build of the addon for Linux and MacOS

build.py, requirements.txt, src/hydrarpr/__init__.py, src/hydrarpr/preferences.py, src/hydrarpr/render_studio/__init__.py
* Added Python deps to `requirements.txt`.
* Adjusted and improved the build script.
* Changed default `workspacedir` to `%ProgramData%/AMD/AMD RenderStudio/Workspace`.
* Updated `RenderStudioKit` SDK.
=> BLEN-611: Add support for RenderStudioWatchdog service

build.py
Remote debugger doesn’t work for USD  because there is a lack of flag `/ZI`
Added flag `/ZI` for `relwithdebuginfo` configuration
=> BLEN-614: Fix relwithdebuginfo build
