src/hdusd/mx_nodes/nodes/base_node.py
Standard Surface shader has 'uifolder' attributes in nodedef for grouping inputs.
1. Added button checkboxes to MX nodes with 'uifolder' attributes in nodedef (currently only Standard Surface) and implemented showing/hiding inputs and parameters depending of enabled folders.
2. Added data type to MX node label if it supports several data types.
3. Improved default width of MX nodes.
4. Fixed label for shader input in MX nodes (relates only to Surfacematerial and Volumematerial nodes).
1. Implemented checking 'uifolder' attributes in nodedef and added corresponded properties to MxNode. Implemented MxNode.ui_folders_update() for showing/hiding inputs.
2. Implemented MxNode.draw_label() for showing data type in node label
3. Refactoring: 
- moved MxNodedef class to internal MxNode.NodeDef …
=> RPRBLND-1613: Group inputs in UI for Standard Surface shader

src/hdusd/mx_nodes/node_tree.py, src/hdusd/mx_nodes/nodes/__init__.py, src/hdusd/mx_nodes/nodes/base_node.py
This is regression after #37 when MX operators become not to work after adding id to MX node classes names.
Fixed MX operators.
Changed MX node names by adding mtlx file prefix to class name instead id, adjusted MX operators.
=> Fixed MX operators, improved working with MX nodes

src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/filter.py
Created USD Filter node which outputs USD prims filtered by path pattern.
Added and implemented FilterNode class. USD path filtering is implemented by converting path pattern into regex pattern and checking incoming USD path to match this pattern.
=> RPRBLND-1365: Filter layers.

src/hdusd/engine/viewport_engine.py, src/hdusd/export/camera.py, src/hdusd/export/light.py, src/hdusd/export/mesh.py, src/hdusd/usd_nodes/node_tree.py, src/hdusd/usd_nodes/nodes/base_node.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/usd_nodes/nodes/filter.py, src/hdusd/usd_nodes/nodes/merge.py, src/hdusd/usd_nodes/nodes/usd_file.py
Updating USD node tree stages during nodes, depsgraph or tree changes isn't working good and not optimized. This also fixes #30.
Fixed and improved USD stages updating in USD node tree during nodes properties, depsgraph or tree changes.
1. Improved, optimized and fixed updating algorithm in USD node tree and USD nodes. 
2. Made some refactoring and code improvements.
3. Improved implementation of some nodes: BlenderDataNode, MergeNode.
4. Adjusted other nodes due to USDNode changes.
=> RPRBLND-1703: Fix USD node tree stages updating during nodes, depsgraph or tree changes

src/hdusd/mx_nodes/nodes/base_node.py
Switching channels in nodes doesn't work properly - they stay always active after being switched on.
Fixed switching channels.
- Added verification for folder status.
- Removed unnecessary code (for MaterialX 1.38).
=> RPRBLND-1803: Material X RPR Uber channels not deactivate.

src/hdusd/engine/__init__.py, tools/build.py, tools/build_usd.py, tools/create_libs.py, tools/data/USD.patch
New USD release 21.08 is available and there are updates in HdRPR.
Updated USD to 21.08 release. Updated HdRPR.
1. Updated submodules USD, HdRPR.
2. Created USD.patch which adjusts USD build for HdRPR. Without it HdRPR doesn't build.
3. Adjusted builds: build_usd.py, create_libs.py.
4. Removed hasattr(os, 'add_dll_directory') in engine/\_\_init__.py as not needed.
5. Improvement in build process: added -clean flag to tools/build.py
=> RPRBLND-1845: Update to latest USD and HdRPR

src/hdusd/export/camera.py
Position of rendered objects is not correct if render region is set
Fixed incorrect position of rendered objects if render region is set
1. New formula for aperture offset for perspective camera
2. New formula for aperture offset for orthographic camera
=> RPRBLND-1816: camera shift support.

src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/root.py
Merge of two or more scenes with the same names in final and viewport render, shows only from the first scene 
Expected merge of the scenes get results from both in the final render
Added new Root node at Add -> USD -> Converters , that allows to create root primitive with specific name and type.
Added and registered class RootNode
Added Root node to Add -> USD -> Converters menu
Added Name field
Added Type field
=> RPRBLND-1836: conflict between the same naming in merged files

src/hdusd/usd_nodes/nodes/merge.py
Merge Node not clean up Inputs
Input sockets amount now correlates with set Inputs
Reworked update method to make correlation work properly
=> RPRBLND-1863: Merge Node not clean up Inputs.

src/hdusd/ui/__init__.py, src/hdusd/ui/render.py
Add "Help/About" UI menu to USD
Added "Help/About" UI menu
Added corresponding panel and operator
=> RPRBLND-1861: Add "Help/About" UI menu to USD.

src/hdusd/bl_nodes/__init__.py, src/hdusd/bl_nodes/nodes/__init__.py, src/hdusd/bl_nodes/nodes/shader.py, src/hdusd/bl_nodes/nodes/vector.py
Add normal map support for MaterialX
Normal now works for MaterialX
Added Normal Map node
=> RPRBLND-1843: Material X Normal Map Support.

src/hdusd/mx_nodes/nodes/base_node.py, src/hdusd/utils/mx.py, tools/generate_mx_classes.py
After refactoring in #99 there are some places in code which should be improved.
- Improved working with _data_types
- Removed \@static made some methods
- Removed unused code
=> Code improvements and some cleanups after refactoring in RPRBLND-1820

README.md
Update Readme.md because it is outdated
Readme.md is up to date
Added Build section
Fixed links
Removed outdated info
Added more explanation to debugging
Chenget sections order
Formatted text
=> RPRBLND-1865: Update Readme.md

src/hdusd/bl_nodes/nodes/shader.py
Need to add support for Principle BSDF Emission channel, now emission doesn't show any results with USD_Hydra plugin
Enable support of Principle BSDF Emission channel
Fixed wrong formula for weight and source for color
=> RPRBLND-1900: Add Principle BSDF Emmision channel Support for USD_Hydra.

src/hdusd/engine/engine.py, src/hdusd/engine/viewport_engine.py
Update Warning image for restart render
Render restarts by itself without warning image if render quality changed
Added creation of new render if render quality changed
=> RPRBLND-1958: Update Warning image for restart render

src/hdusd/ui/material.py
Proposal to add "Convert" label and change button position more intuitive.
Added "Convert" label and change button position.
Changes made to code.
Added bl_label.
Moved HDUSD_MATERIAL_OP_convert_mx_node_tree upper in queue.
Changed  text argument of HDUSD_MATERIAL_OP_new_mx_node_tree.
=> proposal_RPRBLND-1966: Add convert button from blender shader to MatX nodes

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/utils/usd.py
Possible error could happen during rendering with GL
Fixed possible error during rendering with getting render stats.
Fixed: added renderer_percent_done() in utils/usd.py.
Made code improvements.
=> RPRBLND-1995: Error with GetRenderStats().

src/hdusd/config.py, src/hdusd/ui/__init__.py, src/hdusd/ui/material.py, src/hdusd/ui/mx_nodes.py, src/hdusd/ui/render.py, src/hdusd/ui/usd_list.py
Our develop tools in UI should be configurable. There is no need to provide it to users.
Improved some UI panels in USD nodes, MX nodes, Shader editor. Hided develop/debug settings, made them configurable by config.py.
Added show_dev_settings option in config.py. 
Improved UI panels in USD nodes, MX nodes, Shader editor. Added Dev UI panels which is shown by show_dev_settings.
Made some renaming.
=> RPRBLND-2009: Improve working with debug operators and options

src/hdusd/engine/final_engine.py, src/hdusd/engine/viewport_engine.py, src/hdusd/export/material.py, src/hdusd/export/mesh.py, src/hdusd/export/object.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/utils/__init__.py
Reverts GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#156
=> Revert "RPRBLND-1967: Improve "Sync process" for instances"

src/hdusd/engine/preview_engine.py
Fix bug in PreviewEngine.
No more error in console while stretching panel with preview.
Added check for prim validity
=> RPRBLND-2021: Bug in PreviewEngine

src/hdusd/ui/__init__.py, src/hdusd/ui/matlib.py, src/hdusd/utils/__init__.py, src/hdusd/utils/matlib.py
PURPOSE
Improve status update, progress. Handle connection error.
EFFECT OF CHANGE
Added Material Library subpanel Tools with Reload Library button. Improved status. Update sync and download progress. Handle connection error.
TECHNICAL STEPS
Added function update_ui.
Added handle for connection errors.
Added operator HDUSD_MATERIAL_OP_matlib_load.
Added subpanel HDUSD_MATLIB_PT_matlib_tools
=> RPRBLND-1997: Improve Matlib progress + status update

src/hdusd/engine/viewport_engine.py, src/hdusd/usd_nodes/nodes/usd_file.py
Improve USD_Files Import
Added filter input. Animated file now renders with viewport renderer. 
Improve compute method.
Added filter_path property.
Set render params to the current frame.
Animated file now renders with viewport renderer. The final render needs more work, another ticket.
=> RPRBLND-1977: Improve USD_Files Import

src/hdusd/__init__.py, src/hdusd/engine/__init__.py, src/hdusd/export/light.py, tools/build_usd.py
Update USD to 21.11
Submodule USD Updated to 21.11.
- Set deps/USD to 21.11.
- Fixed build script parameters.
- Env var "HD_ENABLE_SCENE_INDEX_EMULATION" set to "false" since UsdImagingLite doesn't work if it's "true".
- Adjusted lights to follow Cycles results.
CIS:REBUILD_DEPS
=> RPRBLND-2036: Update USD to 21.11

src/hdusd/__init__.py, tools/bl_scripts/start_test_addon.py
Adjust code to Blender 3.0+ and fix error messages in console.
Nothing.
- Edited key for bl_info.
- Removed faulthandler to prevent error messages in console.
=> RPRBLND-2075: Adjust code to Blender 3.0+

src/hdusd/mx_nodes/nodes/base_node.py
Fix wrong texture application with GL Delegate.
Texture is applied correctly with GL Delegate.
Removed check if parameter has default value (mtlx file now has all inputs).
=> BLEN-34: Texture coordinates with GL Delegate

README.md, requirements.txt, tools/build.py, tools/build_usd.py
VS 2019 can be recommended to use for building. Also jinja2 python module is required for build.
Updated README with using VS 2019 and python module jinja2. Improved build script.
Updated README.md with using VS 2019. Improved build script.
CIS:REBUILD_DEPS
=> Updated README.md with using VS 2019. Improved build script.

README.md
Typo fixed in paragraph 35
Just to improve documentation. 
Changes made to code: _None_
No  break on code.
=> Syntax issue (paragraph 35) for better documentation

src/hdusd/bl_nodes/__init__.py, src/hdusd/bl_nodes/nodes/converter.py
Fix exception with Round shader node.
Render works properly with Round shader node.
Fixed wrong using of "if_else" method.
=> BLEN-57: [Community] Error with Attic-Demo-CCBY scene.

src/hdusd/properties/object.py, src/hdusd/utils/usd.py, src/hdusd/viewport/usd_collection.py
Fix #179 
Usd scenes with 'Scope' and without type prims renders correctly.
Added 'Scope' prim type to list of supported prim types and pass for typeless prims.
=> BLEN-62: [Community] Failed rendering AnimalLogic USD Lab

src/hdusd/usd_nodes/nodes/usd_file.py
Remove duplicated method from usd_file node
Nothing
Removed duplicated method from usd_file node
=> Remove old duplicated method

src/hdusd/properties/material.py, src/hdusd/properties/object.py
Fix #201 
Undo operation works properly.
Fixed getting strictly first update from depsgraph.
=> BLEN-56: [Community] Undo doesn't work for object, imported from USD file

tools/build_usd.py
Issue #240 
Fixed possible build error "Could NOT find OpenSubdiv".
Added `--force OpenSubDiv` to build USD script
=> Fixed possible error "Could NOT find OpenSubdiv"

src/hdusd/usd_nodes/nodes/__init__.py, src/hdusd/usd_nodes/nodes/filter.py
Add new USD node: Ignore. https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/discussions/204
Added new USD node: Ignore.
Added new USD node: Ignore.
=> BLEN-54 [Community] Improve filter usd node

CHANGELOG.md, src/hdusd/__init__.py
Upcoming release in May 2022
Release in May 2022
Incremented version to 1.1.0.
=> Release May 2022

src/hdusd/properties/scene.py
rename "Prman" to "Render Man".
Change Prman delegate name to RenderMan.
Improved condition for _render_delegates.
=> BLEN-117: rename "Prman" to "Render Man"

src/hdusd/export/mesh.py, src/hdusd/export/object.py, src/hdusd/ui/usd_list.py, src/hdusd/usd_nodes/nodes/blender_data.py, src/hdusd/usd_nodes/nodes/usd_file.py, src/hdusd/usd_nodes/nodes/write_file.py, src/hdusd/utils/usd.py
Add support for Armature modifier.
Added support for Armature modifier.
- refactoring
- added writting mesh deformation to USD at time samples
- fixed set_timesamples_for_prim setting wrong returns in case of multiple attributes with time samples
=> BLEN-158: improve Animation "Export import"

src/hdusd/export/material.py
Material doesn't update on import from MatX library if render enabled.
Material updates properly when import from MaterialX Library during viewport render.
Implement additional functionality to function sync_update_all, cleared references and rebind material.
=> BLEN-214: Material doesn't update on import from MatX library if render enabled

README.md
Update readme.
Updated readme.
=> BLEN-510: Update readme for BlenderUSDHydraAddon

build.py, patches/hdrpr_libs.diff
Add build on Ubuntu
Fix build process and patch for HdRPR
=> BLEN-562: Add build on Ubuntu

build.py
Adjusted build process for changes in https://github.com/Radeon-Pro/RenderStudioKit/tree/bnagirniak/blender-support-python
Use https://github.com/Radeon-Pro/RenderStudioKit/tree/bnagirniak/blender-support-python
=> BLEN-589: Update RenderStudioKit

src/hydrarpr/preferences.py, src/hydrarpr/render_studio/resolver.py
Updated RenderStudioKit SDK using  https://github.com/Radeon-Pro/RenderStudioKit/tree/bnagirniak/blender-support.
Adjusted code according to the RenderStudioKit API.
Remove redundant UI elements from Preferences.
Fix: turned off live sync if it's not enabled.
=> BLEN-600: Implement file synchronization

build.py, src/hydrarpr/__init__.py, src/hydrarpr/logging.py, src/hydrarpr/preferences.py, src/hydrarpr/properties.py, src/hydrarpr/render_studio/__init__.py, src/hydrarpr/render_studio/operators.py, src/hydrarpr/render_studio/resolver.py, src/hydrarpr/render_studio/ui.py
Some code cleanup and UI improvements are required
Improved Resolver class, simplified some code.
Improved Preferences.
Improved working with configdev.py
=> BLEN- 605: Code and UI Improvements

build.py, src/hydrarpr/render_studio/resolver.py
* Updated RenderStudioKit submodule.
* Adjusted build script to latest RenderStudioKit.
=> BLEN-615: Update RenderStudioKit submodule

src/hydrarpr/__init__.py
RadeonProRenderUSD submodule has to be updated.
Updated RadeonProRenderUSD with latest RPR 3.1.4.
Moved addon to Community tab.
Updated RadeonProRenderUSD to latest master.
RadeonProRenderUSD is pointed to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/712
=> Updated RadeonProRenderUSD with latest Core 3.1.4
